kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: expense-manager
rules:
- apiGroup: [""]
  resources: ["node", "persistantvolume", "namespace"]
  verbs: ["list", "get", "watch"]