kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: expense-manager
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: expense-manager
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: expense-manager
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: ramesh